### ISSUE TITLE
[Bug] BetterEnchantedBooks + Multiconnect causes NPE on server connect

### ISSUE THREAD

**Issue by taydev** [Bernasss12/BetterEnchantedBooks#15]
**Describe the bug**
When connecting to a server while running both BetterEnchantedBooks and multiconnect (https://github.com/Earthcomputer/multiconnect) on Fabric v1.16.3 (loader ver. 208), a NullPointerException is thrown resulting in the connection to the server being cancelled.

**To Reproduce**
1: Install both BetterEnchantedBooks (v1.1.2) and multiconnect (v1.3.22)
2: Attempt to connect to a server
3: NPE gets thrown

**Expected behavior**
Instead of the NPE being thrown, server connection continues as normal and allows you to connect.

**Screenshots**
N/A, as connecting simply shows `java.lang.NullPointerException`

**Please include:**
 - Minecraft Version: 1.16.3
 - BetterEnchantedBooks Version: 1.1.2 (obtained from https://www.curseforge.com/minecraft/mc-mods/better-enchanted-books/files/3054237)
 - multiconnect Version: 1.3.22 (obtained from https://www.curseforge.com/minecraft/mc-mods/multiconnect/files/3065756)
 - NPE Log: https://hasteb.in/anavekad.rb

I was advised to report this to you guys by Earthcomputer (creator of multiconnect), so I hope this can be resolved soon!

**Comment by Earthcomputer** [comment]
Just to add some information. I analysed the stack trace and took a look at your ItemStack mixin, and I couldn't see anything in there that could cause an NPE because of multiconnect. What's weirder is that they are connecting with 1.16.3, so no multiconnect translation is required. If after debugging this, you find that something is null that should never be null, and you think multiconnect might be causing that, please get back to me :)

**Comment by Bernasss12** [comment]
Thanks for also looking at it, I'm just as confused, I glanced over it yesterday and have no idea what's going on for now. I'll be debugging in a bit.
Thanks for the input :)

**Comment by Bernasss12** [comment]
If the issue persists in any other form feel free to reopen the issue, from my testing it all works now :)

**Comment by taydev** [comment]
Can confirm, issue has now been resolved! Thanks :)
