### ISSUE TITLE
[Bug] Compability with Enchanted Tooltips mod

### ISSUE THREAD

**Issue by lifesketchy10** [Bernasss12/BetterEnchantedBooks#18]
**Describe the bug**
The enchantment description from Enchanted Tooltips will overlap with the applicable icons from this mod. (Sorry if its hard to see)

**Screenshots**
![2020-10-30_16 10 48](https://user-images.githubusercontent.com/71613550/97690518-a7c21900-1acf-11eb-958c-1cc2e21b830f.png)

**Please include:**
 - Minecraft Version: 1.16.3
 - Mod Version 1.1.4
 - Enchanted Tooltips Version 1.3.4

**Comment by Bernasss12** [comment]
Unfortunately I don't there's anything I can do to fix this since both Enchanted Tooltips as well as my mod fully overwrite the original minecraft tooltip in different ways, best thing I can recommend is to disable the icons in my mod's settings. Best case scenario there would need to be a way to add blank lines into Enchanted Tooltips' tooltips in coordination with my mod

**Comment by Bernasss12** [comment]
But then again that's not something I would be able to do from here

**Comment by Bernasss12** [comment]
From what I have seen the other mod in question is at fault here as it completely replaces the vanilla method I inject code into and therefore I don't think I can work around this, unless there is a change in the way the tooltips are generated on their side (in a way that's less destructive for example) I don't think there's much I can do. 
Best thing you could do to not deal with the issue is to either disable the icon rendering on my side or to disable the tooltips on books on the Enhanced Tooltips mod.
Sorry for the trouble and also I don't mean to offend anyone I just think that there's a way to manipulate tooltips (specifically when appending enchantments) without making it impossible for other mods to inject to the same method.
