### ISSUE TITLE
[Bug] Order is Wrong

### ISSUE THREAD

**Issue by fooeyround** [Bernasss12/BetterEnchantedBooks#39]
**Bug**
I put an Efficiency 5 and Silk Touch together and I tried changing some settings but It still puts The Efficiency 5 on top either way I add them (Client side), I checked it does not happen on the server I play on without the mod, and the color is always Efficiency 5, Even when I have it as a Silk Touch book.

**To Reproduce**
Put Books in anvil and see for yourself With Normal configs, I just add glint back and changed some colors

**Expected behavior**
It puts it on silk touch color

**Screenshots**
well if you need I can send

**Please include:**
 - Minecraft Version: 1.16.5
 - Mod Version 1.2.9
 - Dependencies or other mod's versions (only necessary in case the bug is directly connected to another an interaction with another mod)

**Comment by fooeyround** [comment]
https://user-images.githubusercontent.com/75762996/124698872-9d49f180-de9e-11eb-8f34-827d20b8ae95.mp4


https://user-images.githubusercontent.com/75762996/124698876-9f13b500-de9e-11eb-83af-833b4189c555.mp4

**Comment by fooeyround** [comment]
The second one in the second one is the correct one and the first in the second vid is the one that is wrong

**Comment by Fourmisain** [comment]
It's not a bug, it's a feature™!

Enchantentments are by default sorted by their name (alphabetically), that's why Efficiency comes before Silk Touch.
If you don't want that you can set Tooltip Sorting Mode to Disabled.

**Comment by fooeyround** [comment]
I did and it still showed them like hat so I have to restart my game or f3 t after?

**Comment by fooeyround** [comment]
I thought it was a feature but the setting did not change it for me

**Comment by Fourmisain** [comment]
> I have to restart my game or f3 t after?

You change the Tooltip Sorting Mode in the config and hit "Save & Quit", other than that, nothing needs to be done.

> but the setting did not change it for me

Hm.. I just tested this:

With disabled sorting I put Silk Touch + Efficiency on a book and that turned into a "Silk Touch, Efficiency" book like expected.
I then put Efficiency + Silk Touch on another, which turned into "Efficiency, Silk Touch" - also like expected.
I then switched to alphabetical sorting and both showed up as "Efficiency, Silk Touch", again as expected.
While in alphabetical sorting mode I created another pair of books, one with Silk Touch first, one with Efficiency first - they all looked the same, as expected.
When I disabled sorting again, the pairs of books where I put Silk Touch first showed up as "Silk Touch, Efficiency" books - just like expected.

So I'm not sure what you are seeing, are you sure you combined the books in the right order?
Also, are you sure you are using version 1.2.9?
Because there was a bug before that that made is so that the sorting mode actually changed the books (and enchanted items) themselves instead of just the tooltip.
